# Generated by Django 4.2 on 2024-04-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlatiumTrophyTracker_app', '0002_useraccount_title_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trophytracker',
            old_name='gameDifficulty',
            new_name='game_difficulty',
        ),
        migrations.RenameField(
            model_name='trophytracker',
            old_name='gameTitle',
            new_name='game_title',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='title',
            new_name='user_name',
        ),
    ]
