# Generated by Django 4.2 on 2024-04-04 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PlatiumTrophyTracker_app', '0003_rename_gamedifficulty_trophytracker_game_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophytracker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
