# Generated by Django 4.2 on 2024-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatiumTrophyTracker_app', '0004_trophytracker_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophytracker',
            name='trophy_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
    ]
