# Generated by Django 4.2 on 2024-04-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatiumTrophyTracker_app', '0005_trophytracker_trophy_list_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophytracker',
            name='game_choices',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='trophytracker',
            name='trophy_list',
            field=models.TextField(default=''),
        ),
    ]
