# Generated by Django 4.2 on 2024-04-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatiumTrophyTracker_app', '0006_trophytracker_game_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophytracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
